#+TITLE: Forgecast

* Introduction

Forgecast provides a set of helper functions that allow the user to
link various resources to the forge that hosts them. Forgecast is an
amalgamation of the words "forge" and "cast"; it should be thought of
as a tool to "cast resources to their forges".

/Who is it for?/

If you have built a blog on top of the Org Mode ecosystem of
libraries, for example [[https://orgmode.org/manual/Project-alist.html][org-publish-project-alist]], then this package
may help you address transparency by linking your blog posts to their
original source, as well as a detailed list of revisions that have
affected their content. 

The only requirement is that your blog's source code must be public.

For more information, see my publication on [[https://grtcdr.tn/posts/2022-10-08]["Linking articles to their
version control system to effectively track changes"]].

* Usage

Forgecast is an extension of [[https://orgmode.org/manual/Publishing.html][Org Mode's publishing feature]], and should
therefore be called from a publishing script, i.e. your
website/project specification.

See the examples directory for a much more detailed explanation.

* Installation

Find a project you wish to extend with Forgecast's capabilities and
clone the project.

#+begin_example
git clone https://github.com/grtcdr/forgecast.git
#+end_example

In your publishing script, you will want to redefine
=org-html-format-spec= so as to include the links provided by
Forgecast in your HTML (or even LaTeX) document.
