#+TITLE: Liaison

Liaison generalizes and automates the process of linking an /HTML/
document to its corresponding source document originally written in
the /Org/ markup language. Liaison generates URLs that point to a
specific page in a Git web interface, e.g. the tree, blob, blame, edit
pages, and more.

For more information on how to use and integrate the package into your
project, you are encouraged to read the [[https://grtcdr.tn/liaison/manual/liaison.html][online manual]].

* How does it work?

Check out [[https://grtcdr.tn/liaison][the project's website]] to get a feel for what the package can
do. Although it may not seem like it, the hompage gives a
comprehensive tour of the functionalities of the package.

* Who is it for?

Anyone with a blog or documentation website built on top of the
=org-publish-project-alist= variable provided by the built-in
=ox-publish= library or high-level static site generators such as
[[https://ox-hugo.scripter.co/][ox-hugo]].

* What web interfaces does it support?

- GitHub
- GitLab (and custom instances)
- SourceHut (and custom instances)
- Gitea (and custom instances)
- cgit instances

* Who's using it?

- [[https://grtcdr.tn][grtcdr.tn]], in the postamble of blog posts.
- [[https://ushin.org][ushin.org]], in the postamble of every page.

If you are using Liaison in your project and would like to be included
in the list, feel free to [[mailto:tahaaziz.benali@esprit.tn][contact me]].
