#+TITLE: Forgecast

* Introduction

Forgecast provides a set of helper functions that allow the user to
link various resources to the forge that hosts them. Forgecast is an
amalgamation of the words "forge" and "cast"; it should be thought of
as a tool to "cast resources to their forges".

/Who is it for?/

If you have built a blog on top of the Org Mode ecosystem of
libraries, for example [[https://orgmode.org/manual/Project-alist.html][org-publish-project-alist]], then this package
may help you address transparency by *automatically* linking your blog
posts to their original source for you, as well as other types of
content like the resource's changelog or its raw format.

The only requirement is that your blog's source code must be public.

* Usage

Forgecast is an extension of [[https://orgmode.org/manual/Publishing.html][Org Mode's publishing feature]] and should
therefore be called from a publishing script, i.e. your
website/project specification.

See the provided [[https://github.com/grtcdr/forgecast/tree/example][example]] for a minimal working example and then visit
[[https://grtcdr.tn/forgecast][the published website]] for a live demonstration.

* Installation

- Find and navigate to a project you wish to extend with Forgecast's
  capabilities.

- Now, clone the project:

  #+begin_example
  git clone https://github.com/grtcdr/forgecast.git
  #+end_example

- Or add it as a submodule:

  #+begin_src
  git submodule add https://github.com/grtcdr/forgecast.git
  #+end_src

* Supported forges

| Forge     | Tree | Log | Blob |
|-----------+------+-----+------|
| GitHub    | ✓    | ✓   | ✓    |
| SourceHut | ✓    | ✓   | ✓    |
