#+TITLE: Forgecast

* Introduction

Forgecast generalizes and automates the process of linking an /HTML/
document to its corresponding source document originally written in
the /Org/ markup language. Forgecast generates URLs that point to a
specific page in a Git web interface, e.g. the tree view, the blob,
the blame or edit page, etc.

/How does it work?/

Check out [[https://grtcdr.tn/forgecast][the example website]] to get a feel for the package.

/Who is it for?/

Anyone with a blog or documentation website built on top of the
=org-publish-project-alist= variable provided by the =ox-publish=
library.

/What web interfaces does it support?/

- GitHub
- GitLab (and custom instances)
- SourceHut (and custom instances)
- Gitea (and custom instances)
- cgit instances

See the [[#custom-instances][Custom instances]] section for more information.

* Installation

Find and navigate to a project you wish to extend with Forgecast's
capabilities.

Now, clone the project:

#+begin_src sh
git clone https://github.com/grtcdr/forgecast.git
#+end_src

Likewise, you may choose to add it as a submodule:

#+begin_src sh
git submodule add https://github.com/grtcdr/forgecast.git
#+end_src

* Usage

Forgecast is an extension of [[https://orgmode.org/manual/Publishing.html][Org Mode's publishing feature]] and should
therefore be called from a publishing script, i.e. your project
specification.

- For a minimal working example, check out [[https://github.com/grtcdr/forgecast/tree/example][the example branch]].
- For something more guided, read [[file:GUIDE.org][this document]].

* Custom instances
:PROPERTIES:
:CUSTOM_ID: custom-instances
:END:

Forgecast by default doesn't recognize domains beside the presets, so
you'll have to specify the domain of your forge and its associated
resource URL builder.

Now, suppose you're a member of [[https://www.freedesktop.org/wiki/][freedesktop.org]], your wonderful
projects are present in the GitLab instance provided by your
organization.

To add support for your infrastructure, you need to customize the
=forgecast-forge-alist= variable, here's an example:

#+begin_src emacs-lisp
(defvar forgecast-forge-alist
  '(("gitlab.freedesktop.org" . #'forgecast--build-gitlab-resource-url)))
#+end_src

You should now be comfortable with the way this library works, enough
to make it work for whatever forges you're currently using.
