#+TITLE: Liaison

Liaison, [[https://github.com/grtcdr/forgecast/issues/4][originally named "Forgecast"]], generalizes and automates the
process of linking an /HTML/ document to its corresponding source
document originally written in the /Org/ markup language.

Liaison generates URLs that point to a specific page in a Git web
interface, e.g. the tree, blob, blame, edit pages, and more.

For more information on how to use and integrate the package into your
project, you are encouraged to read the [[https://grtcdr.tn/liaison/manual/liaison.html][online manual]].

/How does it work?/

Check out [[https://grtcdr.tn/liaison][the project's website]] to get a feel for what the package can
do.

/Who is it for?/

Anyone with a blog or documentation website built on top of the
=org-publish-project-alist= variable provided by the =ox-publish=
library.

/What web interfaces does it support?/

- GitHub
- GitLab (and custom instances)
- SourceHut (and custom instances)
- Gitea (and custom instances)
- cgit instances
