#+TITLE: Forgecast

* Introduction

Forgecast provides a set of helper functions that allow the user to
link various resources to the forge that hosts them. Forgecast is an
amalgamation of the words "forge" and "cast"; it should be thought of
as a tool to "cast resources to their forges".

/Who is it for?/

If you have built a blog on top of the Org Mode ecosystem of
libraries, for example [[https://orgmode.org/manual/Project-alist.html][org-publish-project-alist]], then this package
may help you address transparency by linking your blog posts to their
original source, as well as a detailed list of revisions that have
affected their content.

The only requirement is that your blog's source code must be public.

For more information, see my publication on [[https://grtcdr.tn/posts/2022-10-08]["Linking articles to their
version control system to effectively track changes"]].

* Installation

Find a project you wish to extend with Forgecast's capabilities and
clone the project inside of it.

#+begin_example
git clone https://github.com/grtcdr/forgecast.git
#+end_example

* Usage

Forgecast is an extension of [[https://orgmode.org/manual/Publishing.html][Org Mode's publishing feature]] and should
therefore be called from a publishing script, i.e. your
website/project specification.

See the provided [[https://github.com/grtcdr/forgecast/tree/example][example]] for a minimal working example and then visit
[[https://grtcdr.tn/forgecast][the published website]] for a live demonstration.

* Supported forges

| Forge     | Tree | Log | Blob |
|-----------+------+-----+------|
| GitHub    | ✓    | ✓   | ✓    |
| SourceHut | ✓    | ✓   | ✓    |
